@MiniAPI_HostAddress = https://localhost:7216
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJGSUEiOiI0NiIsImV4cCI6MTc2NDg0NjMwMywiaXNzIjoiTWVpbkFwaVNlcnZlciIsImF1ZCI6Ik1laW5BcGlDbGllbnQifQ.lpyySFIU_OszWdPcoiaV6ptbxHK9nXsxdypJmaOk-fE


GET {{MiniAPI_HostAddress}}/products
Accept: application/json

###GET Product by ID

GET {{MiniAPI_HostAddress}}/products/3?Key=test1234
Accept: application/json

###GET Privat
GET {{MiniAPI_HostAddress}}/privat
Accept: application/json
Authorization: Bearer {{token}}

### LOGIN
POST {{MiniAPI_HostAddress}}/login
Content-Type: application/json
{
    "username": "user",
    "password": "password"
}
### Get Product by invalid ID
GET {{MiniAPI_HostAddress}}/products/346

### POST Create a new Product
POST {{MiniAPI_HostAddress}}/products
Content-Type: application/json
{
    "name": "Keyboard",
    "price": 19.99,
    "stock": 100
}

### PUT Update an existing Product
PUT {{MiniAPI_HostAddress}}/products/6
Content-Type: application/json
{
    "name": "Case",
    "price": 29.99,
    "stock": 150
}
### DELETE Remove a Product
DELETE {{MiniAPI_HostAddress}}/products/2

### DELETE Remove a invalid Product
DELETE {{MiniAPI_HostAddress}}/products/659425


### GET All Products after Deletion
GET {{MiniAPI_HostAddress}}/products
Accept: application/json

### POST Create Batched Products
POST {{MiniAPI_HostAddress}}/products/batch
Content-Type: application/json
[
    {
        "name": "Webcam",
        "price": 49.99,
        "stock": 75
    },
    {
        "name": "Headphones",
        "price": 89.99,
        "stock": 50
    },
    {
        "name": "Microphone",
        "price": 129.99,
        "stock": 30
    }
]